### ISSUE TITLE
Problema gestione Enumerazione

### ISSUE THREAD

**Issue by gianluca-regoli** [EtheaDev/InstantObjects#2]
Definita una enumerazione, il sistema gestisce correttamente la creazione della tabella, ma in selezione restituisce un errore di casting perché cerca di trasformare l'intero in variant

**Comment by carloBarazzetta** [comment]
Buongiorno Gianluca, puoi essere più preciso dandomi un esempio di quello che stai facendo?

**Comment by gianluca-regoli** [comment]
Buongiorno,
ho creato una classe dove ho inserito un campo enumerazione
TStatoRecord = (srAttivo, srInattivo, srObsoleto, srSospeso,
srNascosto,srProtetto);
La tabella è stata creata sotto MS-SQL ed il collegamento è stato fatto
utilizzando ADOConnection.
Nella form ho inserito un InstantSelector, quando richiamo la funzione open
il sistema mi restituisce l'errore di conversione variant.


Il giorno lun 18 gen 2021 alle ore 11:43 Carlo Barazzetta <
notifications@github.com> ha scritto:

**Comment by carloBarazzetta** [comment]
Allegami la unit del Modello dati che InstantObject ti ha creato che faccio delle verifiche...

**Comment by gianluca-regoli** [comment]
Buongiorno, in allegato un piccolo esempio dove si verifica il problema.
Quando vado in modifica o inserimento si verifica l'errore.

Il giorno mar 19 gen 2021 alle ore 09:46 Carlo Barazzetta <
notifications@github.com> ha scritto:

**Comment by carloBarazzetta** [comment]
Con la nuova versione 2.9 ho provato ad aggiungere un campo enumerativo nel test model ed ho fixato il problema.
Prova a vedere se ti funziona ora.
P.S. l'allegato del post precedente non l'ho trovato...

**Comment by gianluca-regoli** [comment]
Era un piccolo progetto che simulava il problema... comunque grazie per la mail... domani aggiorno e ti faccio sapere... grazie ancora per la disponibilità...
Per me è un primo approccio al linguaggio ed ogni informazione è fondamentale...

Inviato da iPhone
