### ISSUE TITLE
Problema di gestione della specifica IN nel command di InstantSelector

### ISSUE THREAD

**Issue by gianluca-regoli** [EtheaDev/InstantObjects#3]
Quando si cerca di utilizzare la clausola sql IN il sistema accetta solo un valore all'interno delle parentesi. Mettendo due valori il sistema segnala che si aspetta la parentesi e non la virgola.

**Comment by carloBarazzetta** [comment]
Buongiorno, premesso che il linguaggio IQL sviluppato alle origini dagli autori di InstantObjects non prevede l'uso di "IN", nel corso del tempo in Ethea  abbiamo introdotto quella clausola per poter gestire alcuni casi specifici ma poi è necessario utilizzare le parentesi quadre per specificare lo statement in liguaggio SQL nativo e non più in IQL.
In realtà poi è stato aggiunto un ulteriore supporto alle clausole EXISTS e USING che permette di continuare ad utilizzare la sintassi IQL e far tradurre lo statement SQL a InstantObjects.
Ti allego un documento che fa parte del nostro prodotto InstantSolutions Framework che è basato su InstantObjects: al capitolo 5.1.1 trovi spiegato in dettaglio come fare.
[InstantSolutions_Crash_Course.pdf](https://github.com/EtheaDev/InstantObjects/files/5829703/InstantSolutions_Crash_Course.pdf)
