### ISSUE TITLE
Installazione Componenti in Rad Studio 11 Professional

### ISSUE THREAD

**Issue by gianluca-regoli** [EtheaDev/InstantObjects#6]
Quando installo i componenti dal Package Manager la compilazione va in errore 
nella sezione Compiling project IOFireFAC.dproj ed il pacchetto non viene installato.

**Comment by carloBarazzetta** [comment]
Ho fatto un aggiornamento per Delphi 11.1, attenzione che i nomi (LibSuffix) dei package per D11 sono cambiati.

**Comment by JBee2022** [comment]
RAD Studio 11.1 Professional

InstantObjects does not install. Fails with 'FireDACODBCDriver' not found.

Does InstantObjects work in Delphi 11.1 Professional?

**Comment by carloBarazzetta** [comment]
Yes, InstantObjects works also in Professional version, but you must remove the dependencies of Units that uses some technologies/databases not supported in in Professional version.
I haven't Professional Version installed at the moment to try...
(scrivimi in privato se vuoi su carlo.barazzetta@ethea.it) magari riusciamo a sentirci direttamente.

**Comment by carloBarazzetta** [comment]
Hy James, try to change this section into InstantFireDAC.pas:
// Supported databases  (only MSSQL and Firebird have been tested)

//{$DEFINE SYBASE_SUPPORT}
{$DEFINE MSSQL_SUPPORT}
{$DEFINE IBFB_SUPPORT}
{$DEFINE ORACLE_SUPPORT}
//{$DEFINE PGSQL_SUPPORT}
//{$DEFINE MYSQL_SUPPORT}
//{$DEFINE SQLITE_SUPPORT}

Disabling, {$DEFINE MSSQL_SUPPORT} that probably is the cause of the error and {$DEFINE ORACLE_SUPPORT}.
I don't know specific limitation to FireDAC into Delphi Professional, but if you can use FireDAC with local databases, such as SQLLITE or Interbase/Firebird, you probably must activate only those compiler directive....

**Comment by carloBarazzetta** [comment]
Any feedback?

**Comment by gianluca-regoli** [comment]
I can install the professional version in my new computer, because my old computer no longer works…Inviato da iPhoneIl giorno 22 ott 2023, alle ore 10:18, Carlo Barazzetta ***@***.***> ha scritto:﻿
Any feedback?
