### ISSUE TITLE
Instruction manual

### ISSUE THREAD

**Issue by TheStranger25** [EtheaDev/InstantObjects#7]
Hi, is there a guide or manual that describes in detail the various steps to follow to use the ORM. I saw that in the Demo Intro there is some code but a guide that describes the various components such as the TIstantSelector for example would be very useful. Thanks

**Comment by carloBarazzetta** [comment]
A very complex demo is located into \Demo\PrimerCross, and a complete manual is present here, in the [wiki section](https://github.com/EtheaDev/InstantObjects/wiki) of the project!

**Comment by TheStranger25** [comment]
Ah ok thanks, if I have any doubts, it's the case to create other issues or I use this one or I don't know...

**Comment by carloBarazzetta** [comment]
you can use this issue...
